### ISSUE TITLE
Where to get new firmwares from

### ISSUE THREAD

**Issue by jvitkauskas** [dgiese/dustcloud#1]
Is there a way to download latest firmware without risking installing it on the device?

**Comment by dgiese** [comment]
Hi, technically there is, i will upload some infos later. I uploaded the Version 3094 now. However i did not test it yet in terms of rooting.

**Comment by jvitkauskas** [comment]
Thanks. I cannot check the app as I don't have the device yet. Also, it would great if you could add a link to http://dontvacuum.me/ in README.md if you intend to post something more there.

**Comment by Flole998** [comment]
3094 and even 3124 work. No issues when rooting them. I'm also curious about how you know which is the latest firmware and where it can be downloaded.

**Comment by linuxlurak** [comment]
@Flole998 could you upload  	v11_003132 to your fork? would be super nice!

**Comment by Flole998** [comment]
3132 is more than 100 MB, so it's not possible. You can however try my App if you just want to install it without any modifications

**Comment by linuxlurak** [comment]
Chek this one:
https://dustcloud.seemoo.de/public/xiaomi.vacuum.gen1/original/encrypted/

**Comment by linuxlurak** [comment]
question still persists further on: how did you grad those files? is there a technique to predict the links?

**Comment by dgiese** [comment]
You can read them in the dustcloud or in the logs of the vacuum.
