### ISSUE TITLE
Gen1 firmware 3.3.9_003194

### ISSUE THREAD

**Issue by akeilox** [dgiese/dustcloud#107]
Can anyone comment if the dustcloud still applicable, whom updated their 1st gen Mi robot to firmware version 3.3.9_003194 

I have not been following the discussion actively for some time, not sure if they changed the password/the-hacking-method used by dustcloud.

Someone on robotreviews claims they can see Zone Cleaning in latest version of 1st Gen robot;
http://www.robotreviews.com/chat/viewtopic.php?f=6&t=19479&p=147465#p147465

**Comment by akeilox** [comment]
I can see latest firmware 3194 is already uploaded at https://dustcloud.seemoo.de/public/xiaomi.vacuum.gen1/original/encrypted/

But does it mean hacking still supported or is it uploaded there auto-magically via a script when new firmware is released by xiaomi?

**Comment by hellfi** [comment]
building and flashing still works, upgraded from 096 without reset with known token and flasher.py.
There are some changes, the token is now encrypted(?) in a different file, and not visible in all the log files
I'm not using the local server, not sure if this still works as before
