### ISSUE TITLE
Send command with params ?

### ISSUE THREAD

**Issue by Galoula** [dgiese/dustcloud#122]
Hi,

I think there is a problem with "params" when we try to send a command, I see the issue #113 and I have same problem, but I have on ALL command with "params".

Exemple:
Method: set_custom_mode
Params: 80 (or [80] or '80' or "80" or ['80'] or ...)
Not change the value.

whem I tryp get_custom_mode (without params of course):
I have always:
id : 1521
did : 64523533
data : {'id': 39, 'result': [**100**]}
direction : client >> dustcloud
timestamp : 2018-05-12 13:57:47 

What append ?

I have try directly on command line:
like this for exemple (I have try MANY things ...)
wget --save-headers -O - -o /dev/null "http://10.33.20.11:1121/run_command?did=64523533" --post-data='cmd=set_custom_mode&params={80}'
I have this results:
Sartrouville : Value: {'data': {'value': {'method': 'set_custom_mode', 'id': 40, 'from': '4', 'params': '{80}'}}, 'header': {'value': {'length': 0, 'device_id': b'\x03\xd8\x8d\r', 'ts': datetime.datetime(2018, 5, 12, 13, 59, 22, 383802), 'unknown': 0}}, 'checksum': 0}

I see the params, is ALWAYS between single quote (normal ?).

But this works well (no params ...)
wget --save-headers -O - -o /dev/null "http://10.33.20.11:1121/run_command?did=64523533" --post-data='cmd=app_start'

How I can send params with WEB UI or command line ? Nothing work whit params :'(

EDIT:
Why on other tools I can see:
Sartrouville : Value: {'method': 'props', 'id': 95184893, 'params': {'fan_power': 10}}
But with dustcloud I have:
wget --save-headers -O - -o /dev/null "http://10.33.20.11:1121/run_command?did=64523533" --post-data='cmd=props&params={"fan_power": 10}'
->
Sartrouville : Value: {'id': 46, 'result': 'unknown_method'}

Thanks

**Comment by Petititi** [comment]
Hi!
I have the same problem here, and I found that the problem is that server.py is not handling parameters properly. We need to send them as array of integer, but the script send them as a string. I'm not fluent with Python so I don't know how to properly do this...
