### ISSUE TITLE
map coordinates in Dustcloud / SQL

### ISSUE THREAD

**Issue by florie1706** [dgiese/dustcloud#128]
Hi there,

ist there any chance to have the map coordinates (the live map within dustcloud is written by map coordinates, right?) saved to dustcloud / to my sql server, so I can figure out map coordinates afterwads for zone creation?

**Comment by jschmer** [comment]
The live map stuff happens in https://github.com/dgiese/dustcloud/blob/a40fb5f21382c94b0cbd7b637ffee1e766ee5641/dustcloud/server.py#L111 and https://github.com/dgiese/dustcloud/blob/a40fb5f21382c94b0cbd7b637ffee1e766ee5641/dustcloud/build_map.py#L20
You can probably figure out how to get and store map coordinates from there.
The slam_log_data is the SLAM log from /var/run/shm/SLAM_fprintf.log and map_image_data is the map data from /var/run/shm/*.ppm.
