### ISSUE TITLE
Are there any plans for root new vacuum models - Xiaowa?

### ISSUE THREAD

**Issue by Asdertila** [dgiese/dustcloud#133]
There are 2 new models:
Xiaowa C1 Lite / 1600Pa
Xiaowa E20 Route Planning version / 1800Pa
The manufacturer also Roborock, I think technically not very different from Gen1&Gen2.

**Comment by dgiese** [comment]
No, at least from my side.
The vacuums are without LIDAR and using an ESP8266 as the application processor (instread of the ARM Quadore Allwinner R16 running Linux). I assume that the rest of the vacuum might be the same or similaras Gen1+Gen2. But i did not see any teardown pictures yet, and the vacuums do not have any special features (compared to ilife) that i would make sense for me to spend my money on it.
