### ISSUE TITLE
How to put Vacuum Robot Gen1 in unprovisioned mode

### ISSUE THREAD

**Issue by tlpbu** [dgiese/dustcloud#141]
I have built firmware for my Vacuum Robot Gen1 and ...
[Upload manual](https://github.com/dgiese/dustcloud/wiki/VacuumRobots-manual-update-root-Howto#upload-the-firmware-image) says "6. Now press the wifi button on your vacuum" but there is not Wifi button on device only reset pinhole.
![Buttoms](https://image.ibb.co/gWEa29/Screen_Shot_2018_09_12_at_20_04_24.png)

Can anyone clarify how to get Vacuum Robot Gen1 in unprovisioned mode to be able to upload firmware?

**Comment by merlink01** [comment]
You must reset the robot. See this Thread:

https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Robots-Factory-Reset

**Comment by merlink01** [comment]
Oh yes, I think I did it like this:

Hold down the home button and then with a pencil hold down the reset button (while still holding the home button down). It may take a couple tries.

**Comment by tlpbu** [comment]
Thanks @merlink01! That worked.
