### ISSUE TITLE
Xiaomi vacuum cleaner cliff sensors

### ISSUE THREAD

**Issue by Venedikt1988** [dgiese/dustcloud#142]
Does anyone know how to programming switch off vacuum cleaner cliff sensors? One sensors seems to broke up and it constantly showing error to clean the cliff sensors. Cannot fix the problem in service as they don't have them to replace.

**Comment by UomoNero2099** [comment]
Did you find a solution? I have the same problem

**Comment by Venedikt1988** [comment]
Yes, i dismantled it. As long as i do not need cliff sensors i just openned the casing of all cliff sensors and took out the immitting and recieving part and stick them together with scotch. Already working more than one year. The problem seems that one of the infra red diod lost his immision and lit very weak so that reciever cannot see it.

**Comment by Venedikt1988** [comment]
Each sensor separetly with its immitting part. I did not try to find the one eefective, so i did it with all sensors. You can easily find wich one is a problem by cctv camera in ir mode
