### ISSUE TITLE
Error by // mirobo discover --handshake 1

### ISSUE THREAD

**Issue by Knallix** [dgiese/dustcloud#146]
Hello,

I sent the comment : mirobo discover --handshake 1
The following error appears
![vacuum_gen2_importerror](https://user-images.githubusercontent.com/42406048/46212023-4ef28600-c335-11e8-95ce-9c3e60f8bb6a.jpg)

**Comment by rytilahti** [comment]
Try `pip install netifaces`, looks like python-miio is missing that in its setup.py..

**Comment by Knallix** [comment]
ok thanks
