### ISSUE TITLE
Latest firmware?

### ISSUE THREAD

**Issue by olskar** [dgiese/dustcloud#147]
I see that the latest firmware is on this github  for V1 is v11_003254.pkg

however the latest version is v11_003416.pkg

Could anyone upload that so I can root it and upload it to my vacuum? :)

(Or can I extract it somehow and upload it myself?)

**Comment by dugite-code** [comment]
See: https://github.com/dgiese/dustcloud/issues/140#issuecomment-424211278 @dgiese has stated there are currently not well tested

**Comment by dugite-code** [comment]
https://github.com/dgiese/dustcloud/issues/140#issuecomment-433404820

**Comment by dugite-code** [comment]
How to download directly from Xiaomi is now documented [in the wiki](https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Robots-Firmware-download-from-Xiaomi-Servers)

**Comment by olealgoritme** [comment]
v11_003422.pkg was the latest I could find, when I looked yesterday.

https://cdn.awsbj0.fds.api.mi-img.com/updpkg/v11_003422.pkg

**Comment by olskar** [comment]
> v11_003422.pkg was the latest I could find, when I looked yesterday.
> 
> https://cdn.awsbj0.fds.api.mi-img.com/updpkg/v11_003422.pkg

https://cdn.awsbj0.fds.api.mi-img.com/updpkg/v11_003452.pkg today :)

**Comment by FeatureExpert** [comment]
But be careful, highest number != latest version

**Comment by dgiese** [comment]
Please see here: https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Firmware
I would close this issue for now.
