### ISSUE TITLE
v11_001633.pkg v2 firmware

### ISSUE THREAD

**Issue by greenimpala** [dgiese/dustcloud#158]
New firmware is out - has anybody had success rooting with this?

**Comment by FeatureExpert** [comment]
3.3.9_001633 is "old" firmware, you can get root without any issues

**Comment by akeilox** [comment]
Can’t find clarification if following can be still rooted:

V2 firmware v 3.3.9-001702
and
V1 firmware v ...3542

**Comment by greenimpala** [comment]
> 3.3.9_001633 is "old" firmware, you can get root without any issues

Old as in 4 weeks ago or am I misunderstanding - as far as I know this was released recently (see [post](http://en.miui.com/thread-4531308-1-1.html) on official forum).

**Comment by dgiese** [comment]
Check the temp folder link on the wiki page about Firmware. The filedates reflect the real date when the firmware was build.

**Comment by nicoh88** [comment]
#175
