### ISSUE TITLE
deleted device.conf accidentally

### ISSUE THREAD

**Issue by emilzaman** [dgiese/dustcloud#178]
Hi, If I deleted by accident device.conf there are any possibilities to get the info from the file back?

**Comment by FeatureExpert** [comment]
Which device.conf? There is /mnt/data/miio/device.conf which is symlink to /mnt/default/device.conf.
You can try factory reset too - https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Robots-Factory-Reset

**Comment by emilzaman** [comment]
This device.conf  /mnt/default/device.conf. I've already tried it to factory restore it, no luck, because the folder /mnt/default it's not restored

**Comment by dgiese** [comment]
Hi. Deleting the device.conf is the most severe thing that can happen to you (well, maybe a deleted stm32 is worse). Without it your vacuum will never be able to connect to the cloud again.

For now, I would create a DD image of the default partition and look for the strings did, mac and key. If you are lucky, they might be still there.

Also, if you have an old version of the firmware, look in all the miio logs under /mnt/data (also the compressed ones). Maybe you find there the did and key. The wlanmgr log might give the Mac address.

The last option would be to create a new device.conf with some random data. You would not have cloud connection ever, but you could use offline alternatives (dustcloud, dummy cloud+Valetudo)

**Comment by emilzaman** [comment]
Thanks for the detailed answer. I will look into the dd image maybe I am lucky. If not, I will install dustcloud on my pi ;)

**Comment by emilzaman** [comment]
I've made a dd image of /mnt/default partition, I've searched inside the image after "did" string and I've found all the data there: did, key and mac and this way I was able to restore device.conf
So, thank you very much for your help!
