### ISSUE TITLE
CN to EU conversion - config filename

### ISSUE THREAD

**Issue by unregist** [dgiese/dustcloud#183]
Hi,

Looking at this page:
https://github.com/dgiese/dustcloud/wiki/Vacuum-Robots-CCC-to-CE-conversion
It says to create the file rockrobo.conf in the /mnt/default folder.

On this page:
https://github.com/dgiese/dustcloud/tree/master/devices/xiaomi.vacuum.gen1/CN_to_EU_script
The tar file contains roborock.conf rather than rockrobo.conf

Which one is correct? roborock.conf or rockrobo.conf?

**Comment by dgiese** [comment]
Oh, actually its the same file for both roborock.conf

**Comment by unregist** [comment]
Thanks. I've updated the page to reflect the right filename
