### ISSUE TITLE
audio_generator with mac TTS not working

### ISSUE THREAD

**Issue by hagenuck1** [dgiese/dustcloud#185]
Hi, I just tried to create a new voice file for german language using the audio_generator.py with mac TTS. Creating the file is working fine, I then upload the file using RRCC, but the robot doesn't say anything anymore.

As soon if I override them with  the original english.pkg everything is working again.

Created file is german using Anna (didn't change the py-file) and is 11MB in complete.

EDIT: Just tried "Markus" which isn't working, too.

EDIT2: Just unpacked the english.pkg using RRCC. Packed this one using RRCC and uploaded it. FIle is working. 
Replaced only the "findme.wav" by the german mac TTS file, packed and installed it, but now only the findme audio is missing.

Seems as if the mac TTS wav-files aren't compatible?

**Comment by FeatureExpert** [comment]
Try this way:

1. On mac generate aiff files using 'say' command
2. Use ffmpeg to convert aiff to wave
3. Compress, encrypt, upload...
