### ISSUE TITLE
Alexa/Google Assistant Support?

### ISSUE THREAD

**Issue by Tuckeran5607** [dgiese/dustcloud#19]
Hey guys. Was curious if porting Support for GH or Echo devices would be possible after rooting.

I figure it should. Since all you have to do is send a signal to the device via the Internet to start cleaning...

Anyone smarter than me able to tell me about this?

**Comment by tmechen** [comment]
you can actually achieve this even without rooting. you can add your xiaomi vacuum robot to your custom https://home-assistant.io/ installation. furthermore you can add your alexa etc to your hassio and create custom comands (regarding the vacuum)

**Comment by Flole998** [comment]
Not only home assistant is possible, also OpenHAB and FHEM.

**Comment by frostworx** [comment]
I prefer to (voice) control everything offline. currently snowboy launches my python-miio based scripts. contains a binary blob, but better than a wiretap. generally it is a matter of some basic scripts to control your devices (you need a commandline of course) and those scripts can be implemented everywhere (f.e. domoticz).

**Comment by Tuckeran5607** [comment]
You guys have opened my eyes to a whole new area I didn't know was possible.

Anyone have a write-up or know where I can find one to get started with Alexa? I got my parents a Xiaomi Vac for Christmas, and I was under the impression it would work with the Singapore Server (Google Alexa and Xiaomi Vacuum.) 

But when I tried to set it up for them Christmas Day. The Singapore Server has been shut down apparently. So I was kinda at a loss....

Any help would be great. Im not afraid of scripting. I've got a Degree in IT (Recent Grad). But I'd prefer something with a GUI to setup. Just more comfortable with it...

I really appreciate all the answers each and everyone of you has given me though!

**Comment by Flole998** [comment]
It depends on which system you want to use. You always need some kind of server, usually a raspberry pi or similar is enough, if you have a real server at home it's even better.

I can recommend using OpenHAB, it has a great Webinterface and you can control so many things with it. It integrates with Alexa and the Google home plugin is waiting for approval by google, should be available within a week.

**Comment by Tuckeran5607** [comment]
I don't have access to a server unfortunately. However, I could probably run it on my parents desktop. As they keep it on like, all the time.. OpenHAB? I'll get to reading! Thanks so much.
