### ISSUE TITLE
Xiaomi Mi Gen1 automatic Downgrade

### ISSUE THREAD

**Issue by desq42** [dgiese/dustcloud#199]
Hi,

I presume this is not an issue with dustcloud, but perhaps someone has seen something similar.
I wanted to Root/Flash the newest Firmware to my Gen1 (3.3.9_003600.pkg)
Build and flash works like a charm. My Gen1 flashes and I can briefly access Valetudo 0.2.0 to
check the firmware. Everythings fine. 3-4 Minutes later, my Gen1 reboots and restores it´s old firmware. (3.3.9_3514) incl my previous Root & Valetudo. Has somebody a hint, how to prevent
this behavior? 

Thanks.
Desq

**Comment by cryptomilk** [comment]
Did you follow: https://github.com/dgiese/dustcloud/wiki/Cloud-Free-Firmware-Image-With-Valetudo

**Comment by desq42** [comment]
Yes, I did follow it.

**Comment by cryptomilk** [comment]
The robot uses a A/B system. So it flashes to B and boots it, if everything is fine it flashes to A too, if not it boots to A.

This means something probably crashes and that's why it boot system A again. You probably have to flash again, connect via ssh as soon as possible and tail log files to find out what is happening.

**Comment by desq42** [comment]
okay thanks. I´ll give it a shot.

**Comment by desq42** [comment]
mh. Yesterday I flashed the original FW 3.3.9_003600, but after 3 Minutes it reverted itself back to my rootet & valetudo 3.3.9_003514. WTF?!  It seems as if I´ll have to do a factory-Reset, or has anybody an Idea? Which should I view to fix this issue?

**Comment by cryptomilk** [comment]
FW 3.3.9_003600 is a beta version. The latest official version should be: 003468. Maybe you shouldn't use beta software :-)

**Comment by desq42** [comment]
Good advice. ;-) Where do I get it? 
![bildschirmfoto 2019-03-06 um 10 06 41](https://user-images.githubusercontent.com/18470786/53869035-ac32e780-3ff7-11e9-8ea1-8080d74e7bc3.png)

**Comment by cryptomilk** [comment]
https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Firmware

**Comment by desq42** [comment]
dammit. Same behaviour with v11_003468.fullos.pkg
Seems as if this guy is begging for a factory reset.

**Comment by herrwusel** [comment]
I had the same behaviour and it was gone after a reset. Might be worth trying. Did you change anything on the robot like installing additional packages?

**Comment by desq42** [comment]
except for midnight commander nothing else.
got to search this russian mi home app…
