### ISSUE TITLE
flasher.py vs mirobo update-firmware

### ISSUE THREAD

**Issue by fvollmer** [dgiese/dustcloud#210]
Is there an advantage of using the `flasher.py` (which uses python-miio) vs the [`mirobo update-firmware`](https://github.com/rytilahti/python-miio/blob/master/docs/vacuum.rst#firmware-update) command (provided by python-miio), or is this just an historic artifact?

**Comment by cryptomilk** [comment]
I've recently tested `mirobo update-firmware` and it worked just fine for me. Not sure if flasher.py is still needed.

**Comment by fvollmer** [comment]
`mirobo update-firmware` also worked for me. So `flasher.py` must be a historic relic.

**Comment by imbaimbaimba** [comment]
I was getting Error: No such command for update-firmware. Turns out, the right command is update_firmware. Just in case anyone stumbles in here with the same issue.

**Comment by fvollmer** [comment]
This happens if an outdated (<7) version of `click` is installed. Should be fixed with https://github.com/rytilahti/python-miio/commit/d5e238144fd9743c5b87a04f0bb1262ce9e738c8 (yet to be released).
