### ISSUE TITLE
Same functionality for 360 S6

### ISSUE THREAD

**Issue by saberone** [dgiese/dustcloud#225]
Might be a stupid question. But I’m asking anyway ;) I’m assuming that this firmware will not ever be able to run on de 360 S5/S6. But do you know of any initiative that does the same kinda thing as dustcloud, but for 360 S6?

**Comment by dgiese** [comment]
Not that I am aware of. The problem seems to be also, that it is not easy to get one of them and they potentially do geoblocking due to some patent stuff...

**Comment by cougarten** [comment]
You can get them from aliexpress. There are "world" versions and the chinise versions can be paired by spoofing GPS using VPN for the initial pairing. Cloud works after that.
