### ISSUE TITLE
Emmc flash  of Xiaomi Gen 1  broken

### ISSUE THREAD

**Issue by ibao88** [dgiese/dustcloud#233]
The way I get firmware is to weld the emmc flash chip down ，then firmware is acquired through PROGRAMMER.One problem I have now is that I find boot area 1 and boot area 2 which is 
 in the emmc flash is blank。I restored the emmc chip to PCB and the robot failed to start.
           anybody have  good idea about this，I want to do data recovery and rewrite the data of bootarea to the emmc flash， but I need complete chip data which contains bootarea .is there have the data？

**Comment by dgiese** [comment]
Solved via Email
