### ISSUE TITLE
Back service but more wifi

### ISSUE THREAD

**Issue by Almeyric** [dgiese/dustcloud#234]
Hello,

I have for a year and a half a Mi vacuum Gen1. He was sent back to SAV for the fall detectors. On his return, no more Wifi. The reset does not work, is there any way through the USB connection to connect and solve the problem. I found motherboards on Aliexpress, or I have to send it back to SAV but it's two to three months of waiting.

Waiting for a solution.

Thank you

**Comment by dgiese** [comment]
Not if the adbd binary was replaced (e.g. by a rooted firmware). I would assume that the SAV (?) did not install a custom firmware...
Unfortuantly there is not much you can do without opening the device (which would risk your warranty).
