### ISSUE TITLE
Viomi V2 vacuum support

### ISSUE THREAD

**Issue by MHOOO** [dgiese/dustcloud#236]
Hi,

I own a viomi vacuum, which according to the Internet is very similar to the xiaomi vacuums. At the very least it has ssh running on it and can be controller via the mi home app.

I wonder if trying out the firmware flashing is a good idea, or if I could irreversibly brick the device?

**Comment by flatsiedatsie** [comment]
Where did you read that it can be controlled via the Xiaomi app? I read the opposite, that the app support is poor. https://smartrobotreviews.com/reviews/roborock-s6-vs-viomi-v2.html

**Comment by adam-golab** [comment]
There are 2 versions of the Viomi V2 vacuum. The first one supports only Viomi App. And the second works only with the Mi Home App. If you are lucky and bought the vacuum with the Mijia logo on it, then you can use Mi Home App. 

Both versions have a micro USB port with SSH running. One can connect to it via ADB. I checked the first version and it runs originally on Tina Linux (based on OpenWRT), so I see one difference here, as Xiaomi Mi Robot works on Ubuntu (based on info from https://www.kaspersky.com/blog/xiaomi-mi-robot-hacked/20632/).

**Comment by dgiese** [comment]
I will add support to the dustbuilder in the next days, which will however only work for the Mi Home compatible devices (I bought mine 2 months ago and its already Mi Home compatible). Unfortunately, the original ones do not contain the Mijia Cloud credentials, so there is no real official "upgrade" path for that devices. Due to the Squashfs image and the small NAND flash we are also limited in options like Valetudo. Will keep you updated.

**Comment by hudarsono** [comment]
Any update on this?

**Comment by t0kic** [comment]
Hi @adam-golab. How did you find out about the linux version on the robot? Mine also only supports the Viomi app and has the ports 22, 53, 6000 and 6008 open. 
Perhaps we can work with the xserver ports?

**Comment by dgiese** [comment]
Access to Viomi is, compared to Rockrobo, more simple. I am preparing some tools for it.

**Comment by t0kic** [comment]
That sounds great @dgiese
I also have an viomi v2 and I was thinking to send it back to the vendor due to the very bad viomi app and lack of dustcloud support. 
If I can help somehow or if you need me to test anything on my device please let me know!

**Comment by dgiese** [comment]
If you have a Viomi-App only device, there seems to be an upgrade path to the Mi Home version. I am aware of at least one user who did that. He contacted Viomi via Facebook and they sent him some weird tool for it.

**Comment by t0kic** [comment]
Yes, it is viomi app only device. Could you point me the way to that user or any other help how to change it to mi home version. 
Viomi FB is not responding to any of my messages so far

**Comment by t0kic** [comment]
Thank you!

**Comment by adam-golab** [comment]
@t0kic it usually takes around 5 days to get an answer from them on FB. So you have to be patient.

**Comment by t0kic** [comment]
thanks @adam-golab. I asked them about one week ago, but will be more patient. 
As soon as I have any answer, I will let you know. 
There is a rumor, viomi will stop developing new firmware for the viomi-app only version.

**Comment by adam-golab** [comment]
Yes, I've heard it too. Also, there were rumors that on August they upgrade all devices to Mi Home. But as September starts it only confirms that it was not exactly the truth. 

If you are waiting for an answer one week, I'd recommend asking them once again there. If it possible for you, write to them in their daytime. So around 10am - 4pm GMT+8. I was getting answers mostly around 4-5pm GMT+8. But this is not a general rule as a few times I've got a response on 12am GMT+8

**Comment by t0kic** [comment]
Thanks for the hint @adam-golab! Will write them at that time. 
It is really very good device and it will be shame if I have to send it back.

**Comment by uhrwerk** [comment]
Hi, are there any updates on this? Also got the Viomi App Version and it's so sad that the robot isn't supported anymore by Viomi and won't get updates while the Mi Home does get them. Seems like Viomi on Facebook isn't answering anymore.

**Comment by BackSlasher** [comment]
@dgiese can I use the latest version with a Mi-using Viomi V2?
It's still not in the "supported devices" list, so I'm unsure.
Thanks!

**Comment by t0kic** [comment]
Hi @dgiese !

Would it be possible to use dustcloud or valetudo on Viomi App Version of V2 with root access via ADB?

Thank you!

**Comment by BrendanxP** [comment]
I sent messages to Viomi Facebook, starting from mid October 2019 until mid November. I just noticed they gave me a short reply on January 8 2020. That took almost three months to get a reply, let alone a fix to get Mi Home support.
I was wondering if anyone else has made any progress to get from Viomi App to Mi Home software? Or if anyone got new information about the topic.

**Comment by uhrwerk** [comment]
> I sent messages to Viomi Facebook, starting from mid October 2019 until mid November. I just noticed they gave me a short reply on January 8 2020. That took almost three months to get a reply, let alone a fix to get Mi Home support.
> I was wondering if anyone else has made any progress to get from Viomi App to Mi Home software? Or if anyone got new information about the topic.

In this forum: https://www.roboter-forum.com/index.php?thread/34126-viomi-v-rvclm21b-erfahrungen-fragen-tipps-tricks/&pageNo=30
somebody who tries to find a way to upgrade to the mi version asked recently for data of a v2 mi version. Since then nothing new happened 

Also viomi saw my message on facebook but I'm left on read. I'm done with viomi.

**Comment by bordino** [comment]
Hello 
I have a viomi v2 pro and I installed the update yesterday 3.5.8_0034 everything went well except that there is no longer washing in Y, it washes only in S.
How to put the wash back in Y, please?

![E60FC0FD-EB82-4FD9-8545-30737F59DE51](https://user-images.githubusercontent.com/63489289/79036447-957e9d00-7bc8-11ea-8886-b411a4c8f243.png)
![CB898838-3A12-4362-9AF3-43042FB88E33](https://user-images.githubusercontent.com/63489289/79036451-99122400-7bc8-11ea-91b0-e46b626c11b2.png)


Best regards

**Comment by anywen** [comment]
> Hello
> I have a viomi v2 pro and I installed the update yesterday 3.5.8_0034 everything went well except that there is no longer washing in Y, it washes only in S.
> How to put the wash back in Y, please?
> 
> Firmware 3.5.8_0034
> ![E60FC0FD-EB82-4FD9-8545-30737F59DE51](https://user-images.githubusercontent.com/63489289/79036447-957e9d00-7bc8-11ea-8886-b411a4c8f243.png)
> 
> Firmware 3.5.3_0030
> ![CB898838-3A12-4362-9AF3-43042FB88E33](https://user-images.githubusercontent.com/63489289/79036451-99122400-7bc8-11ea-91b0-e46b626c11b2.png)
> 
> Best regards

I’ve got exactly the same problem with a viomi v2, did you found a workaround for this?
Best regards

**Comment by tomiu** [comment]
In the application go to settings. There you will see "Mop or vacuum & mop mode". Click it and then chose Y-pattern

**Comment by keynight** [comment]
https://github.com/keynight/viomi_v2  
Inside Viomi V-RVCLM21B with ABD/SSH access
