### ISSUE TITLE
Firmware repository for S6 has no English voice

### ISSUE THREAD

**Issue by spang11ers** [dgiese/dustcloud#242]
Hi all,

I noticed that the S6 voice folder has no English voice and also the S6 firmware folder looks like it is actually T6 firmware.

**Comment by dgiese** [comment]
The english voice is already integrated in all firmwares.
About S6 and T6 firmware: You figured out the secret of rockrobo ;) The firmwares are the same...

**Comment by spang11ers** [comment]
Hi Dgiese, ah ok I can't seem to find the english.pkg anywhere in the firmware and it's not an option on the T6 app

**Comment by dgiese** [comment]
No, the files are already there. You need to switch the language over the api.

**Comment by thbl** [comment]
@spang11ers  did you figur out how to change lang with api ?
