### ISSUE TITLE
Can use firmware of gen 2 for Xiaomi Mijia STYJ02YM 2 in 1?

### ISSUE THREAD

**Issue by LuuTinhIT** [dgiese/dustcloud#249]
Hello,
I have Xiaomi Mijia STYJ02YM 2 in 1.
So, i would like use other firmware for my vacuum.
Can use firmware of gen 2 for Xiaomi Mijia STYJ02YM 2 in 1?
Thank you !

**Comment by dgiese** [comment]
No, that model is a different vendor. The rooting of that is WIP, but will likely work differently.
