### ISSUE TITLE
How screwed am I? Repeating flashing process due lost SSH key

### ISSUE THREAD

**Issue by galaris** [dgiese/dustcloud#271]
So I followed the guide [here ](https://github.com/dgiese/dustcloud/wiki/VacuumRobots-manual-update-root-Howto), everyting went fine, I got my ssh.

2 months pass by, I lost my PC where I had my private key, thus I can no longer login.

Can I just repeat this process to flash the firmware again?

**Comment by 77ROMANTIK77** [comment]
yes
