### ISSUE TITLE
Is there a way to get firmware 3.5.3_0047 on viomi v-8(EU)?

### ISSUE THREAD

**Issue by Username-Is-Unavailabl** [dgiese/dustcloud#281]
I want to get the latest firmware (3.5.3_0047) for multi map support and other improvements, but only the China version(viomi v-7) gets the latest firmware updates and the Europe version(viomi v-8) only has the 3.5.3_0017 update
I really need multi map support since my house has two floors
![IMG_20200717_133330.jpg](https://user-images.githubusercontent.com/68369199/87777487-3e750d80-c832-11ea-9a54-1e6e61b5b657.jpg)
![IMG_20200717_133303.jpg](https://user-images.githubusercontent.com/68369199/87777543-58aeeb80-c832-11ea-9545-d6c91c097917.jpg)
Here are a few pictures of the vacuum
It was bought from Eastern Europe(Romania) and it is called the Xiaomi Mi Robot Vacuum Mop Pro

**Comment by dgiese** [comment]
Yes, check https://builder.dontvacuum.me/_viomi_v7.html
This will convert a v7/v8 to a v6 firmwarewise. However, if you already connected the robot to the cloud, it will remember that you have a v8 (at least in that particular region [eu,global/sg, cn, ru]

**Comment by TheWeeezel** [comment]
Could anyone explain how to transfer these fils and flash? There is nothing in the wiki which allows me to understand how to do it. Im an absolute noob but flashed many phones and 3d printers. No idea how to achieve this though
