### ISSUE TITLE
Link to english language pack dead

### ISSUE THREAD

**Issue by anoderay** [dgiese/dustcloud#291]
Within the How-To-Guide (https://github.com/dgiese/dustcloud/wiki/VacuumRobots-manual-update-root-Howto) the Link to the english language pack is dead https://dustbuilder.xvm.mit.edu/pkg/voice/english.pkg.

**Comment by Pedda1983** [comment]
Try this [](https://dustbuilder.xvm.mit.edu/pkg/voice-v1/english.pkg) instead

**Comment by dgiese** [comment]
For reference: https://builder.dontvacuum.me/pkg/
