### ISSUE TITLE
My xiaomi Dreame d9 is dead and no sign of life

### ISSUE THREAD

**Issue by sqlimmajid** [dgiese/dustcloud#313]
Hi Guys,
Please I have an issue with my Dreame Vacuum D9 (dreame.vacuum.p2009) which is dead!! (No interaction, no light, no reaction, …) before that I have switched my Mi Home account from Singapore to French ( because I wanted to link it with my Alexa :frowning :)
It was fully charged and it have requested me to update the firmeware but after that I disovered that the robot is dead and I tried to reset it but no reaction. from that moment I can’t do anything as it is fully Off and no signe of reactvitiy, is like the systeme has been erased or its Soft have been broken due to the firmeware update.
Can you please help me to resolve this issue?
For information, I installed the token extractor and I can see the Vaccum linked in my account Singapore and I can see also its token.
Many thanks for your help and support

**Comment by dgiese** [comment]
If that's still relevant, please create a ticket here: https://vaers.dontvacuum.me
There i might guide you in a direction, that hopefully solves it.
Generally, such cases sound like a warranty problem, especially, as no rooting/custom firmware seems to be involved...
