### ISSUE TITLE
Discussion: S6 pure TTL wiring

### ISSUE THREAD

**Issue by francois-pasquier** [dgiese/dustcloud#315]
Hi, I checked this [thread](https://github.com/dgiese/dustcloud/issues/213#issuecomment-815179142) which includes RX/TX pins for soldering the TTL connection. I was wondering if anyone knows if the same pins are present at the same location on the S6 pure motherboard.

I read that the S6 pure is closely related to the S5 max, that's why I am asking.

**Comment by dgiese** [comment]
Yes, S5 Max, S6 Pure, S7*, S4 Max have more or less the same PCB. The TX/RX pins are the same.
