### ISSUE TITLE
Replace soundpack on roborock s6 pure

### ISSUE THREAD

**Issue by francois-pasquier** [dgiese/dustcloud#319]
Hi, thank you for the hard work!

As the filesystem for /opt is read-only on s6 pure,  I am looking for a solution to replace the installed soundpack.
I tried with Valetudo and it fails with an error 3

I also hope it's the right place to discuss this as the error is coming from `miio_client` when calling `dnld_install_sound`

**Comment by Lanchon** [comment]
in the startup scripts (check your dustbuilder fw home dir for root) you can bind-mount a directory from a writable partition into /opt.
