### ISSUE TITLE
Sound format used

### ISSUE THREAD

**Issue by pr10dr** [dgiese/dustcloud#38]
Iam intrested to change the announcements ("Dustbin removed" etc.) with custom sounds.
Yet i have not found the right settings to export my wav files to be playable on the device.
Does someone have working settings which are either universal across programms or applicable for audacity or ffmpeg?

**Comment by frostworx** [comment]
RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
works fine as well

**Comment by jvitkauskas** [comment]
Use `ffmpeg -i input.mp3 -acodec pcm_s16le -ar 22050 output.wav` to convert sound files

**Comment by bartasdiver** [comment]
V1 doesn't play waves generated by `say` command on mac OS, probably `--data-format=LEF32@22050` is not compatible.
