### ISSUE TITLE
Extending internal storage

### ISSUE THREAD

**Issue by CODeRUS** [dgiese/dustcloud#43]
Any ideas about extending internal storage?
Can usb port be utilized for connecting pen drive?

Current situation is sad enough:
```
root@rockrobo:~# df -h
Filesystem       Size  Used Avail Use% Mounted on
/dev/root        494M  380M   89M  82% /
devtmpfs         202M  4.0K  202M   1% /dev
none             4.0K     0  4.0K   0% /sys/fs/cgroup
tmpfs             30M  4.0K   30M   1% /tmp
none              50M  236K   50M   1% /run
none             5.0M     0  5.0M   0% /run/lock
tmpfs            100M  8.5M   92M   9% /run/shm
none             100M     0  100M   0% /run/user
/dev/mmcblk0p11   16M  2.0M   13M  14% /mnt/reserve
/dev/mmcblk0p1   1.6G  332M  1.2G  22% /mnt/data
/dev/mmcblk0p6    16M  1.2M   14M   8% /mnt/default
/dev/mmcblk0p10  494M  221M  248M  48% /mnt/updbuf
```

**Comment by linuxlurak** [comment]
true. true. Wanted to install some packages since apt is available. vim takes 40mb... vim-tiny only about 300kb. lucky me it's all I want at the moment (besides htop and locate). Have you inserted a stick and checked syslog? Didn't think of the usb port at all till now!

**Comment by dgiese** [comment]
Hi,
so what i did for my dev firmware: I created a symlink for /var/cache (not sure about the folder name at the moment) to /mnt/data/var/... (created new folder on data partition.). I will try to script that, so you can use it. The dpkg package cache + repo information takes already 100mbyte.

USB sticks do not work at the moment, as the kernel do not have the usb storage modules.

**Comment by CODeRUS** [comment]
> kernel do not have the usb storage modules
this is very sad to hear

symlink or bind mount to data partition can work for now

**Comment by dgiese** [comment]
However you could compile a module for that kernel ;)
I am working on a hardware mod for storage, but it will take some time.

**Comment by CODeRUS** [comment]
> you could compile a module for that kernel

info about compiling modules can be useful!

**Comment by linuxlurak** [comment]
Does somebody know if the update routine (where is it? what script?) checks for modifications? I tried to implement a minimalistic http server and tested it with 0033132. After the upgrade the robot behaved very strange and in the end it talked only chinese and reverted the firmware obviously to some backup version... (no ssh etc.).  

If you are interested in the idea of a mini http server check: https://github.com/dgiese/dustcloud/commit/b207c6fc65abb0b4505f32fc899296c621fac65a

**Comment by dgiese** [comment]
So i have also some strange behaviour with 3132. I tried to implement some FHEM based image for you folks, however somehow it did not work. Btw: 3132 have already the integrated english language. However i have no idea how to switch it on.

**Comment by linuxlurak** [comment]
interesting. After the upgrade I had no problem in altering the files and running a http service. but I have to check again to be sure.  Hopefully there are no problems for future updates in case you have done changes to the os... Perhaps we could scan for specific binaries that check for changes. 

Yesterday I tried to check with diff if there are changes in the software.  I lack of methodology and know how to do this...

**Comment by Flole998** [comment]
I use nfs for more storage. Works great.

**Comment by dgiese** [comment]
see script in repo, which used data partition as storage.

**Comment by Galoula** [comment]
You can use olso NFS.

Okay, only througth Wifi and its not the better way, but is possible !
