### ISSUE TITLE
Use chroot and qemu to work with image

### ISSUE THREAD

**Issue by fvollmer** [dgiese/dustcloud#49]
Just as a quick info: You can use chroot and qemu to work with the image. E.g. for software development. This way you won't suffer from the small storage. Obviously there is some performance hit, since the processor emulation.

1. extract rootfs
2. `cp $(which qemu-arm-static) rootfs/usr/bin`
3. `cp /etc/resolv.conf rootfs/etc/resolv.conf`
4. `mount -t proc proc proc/`
5. `mount -t sysfs sys sys/`
6. `mount -o bind /dev dev/`
4. `chroot /mnt qemu-arm-static /bin/bash`

I also had to remove the ppa from `/etc/apt/sources.list`, since some packages were missing.

**Comment by dgiese** [comment]
Hi,
so i had a emulated vacuum running on a orangepi, as it its technically the same hardware. Actually you should be able to chroot on a raspberry pi, as the architecture is the same.
