### ISSUE TITLE
Some questions about symmetric keys encrypt traffic with the cloud.

### ISSUE THREAD

**Issue by skysilver-lab** [dgiese/dustcloud#55]
Hi. Great job. I have a question about the symmetric key to encrypt traffic with the cloud. 
This key is unique for each cleaner? 
As the cloud knows which key is the encryption?
Really in the cloud has keys for each of the cleaner that went on sale?
Is it possible to identify the encryption key to other devices xiaomi such as light bulbs, sockets, humidifiers, etc.?

**Comment by dgiese** [comment]
The cloud encryption key is unique per device and is written at the factory onto the devices. It stays forever. The identification is done over the device ID in the header of the cloud packet.
