### ISSUE TITLE
Grab new v2-image

### ISSUE THREAD

**Issue by itelli** [dgiese/dustcloud#68]
Hello guys,

one question: how to grab a new v2-image? Do i have to connect the vacuum geb2 with the 001168-image first to the dustcloud and can grab a new update via dustcloud?

New-Image 001228 available on china-mainland!

Many thx in advance!

**Comment by MeisterTR** [comment]
now i also see the update. do you use a dustcloud? another way were the miio.log you can accept the update and turn of the wifi a few seconds later so the robot do not update and you see the message withe the firmware link

**Comment by dgiese** [comment]
If you kill ccrypt before updating, then you device is not altered and you can still get the firmware. Might be useful as we dont know what funny things Rockrobo/Xiaomi did in the firmware update ;)

**Comment by itelli** [comment]
Hello MeisterTR,
i want to use the dustcloud, it's already up and und running, but i couldn't add my rooted v2 device...
I have the token, the ip and anything else for the rooting (i used the 001228 from the dustcloud server), but what do i have to enter in the fields "did" and "enckey" on the newdevice.php?
Many thanks in advance!

**Comment by dgiese** [comment]
both information you find after rooting in device.conf.
