### ISSUE TITLE
3.3.9_003096 custom firmware?

### ISSUE THREAD

**Issue by bartasdiver** [dgiese/dustcloud#71]
Does anyone use 3.3.9_003096 firmware and can confirm that after update it is still possible to upload custom firmwares? 
![img_5013](https://user-images.githubusercontent.com/3897949/36077267-0346cd9a-0f69-11e8-80c7-2d79ac316e60.jpg)

**Comment by omp-gluehbirne** [comment]
I can confirm it is still possible. I just installed a rooted 3.3.9_003096 on a non-rooted 3.3.9_003096.
