### ISSUE TITLE
Duplicate files: UPDATE-howto.md and wiki/VacuumRobots-manual-update-root-Howto

### ISSUE THREAD

**Issue by Yky** [dgiese/dustcloud#86]
The following two files seem to be duplicated, which makes them hard to maintain or keep in sync. Can one of them be removed? Maybe the wiki could link to the version-controlled file. 

https://github.com/dgiese/dustcloud/blob/master/devices/xiaomi.vacuum/UPDATE-howto.md 
https://github.com/dgiese/dustcloud/wiki/VacuumRobots-manual-update-root-Howto

**Comment by dgiese** [comment]
I deleted the file. I encourage you guys to edit the wiki, as it is easier than to always update files in the repo ;)
