### ISSUE TITLE
Xiaomi Vacuum Generation 2 - list voice messages

### ISSUE THREAD

**Issue by kowalczykrafal** [dgiese/dustcloud#91]
Hello,

Will I find somewhere a list of voice messages for xiaomi vacuum 2 generation? I would like to create a new language for Vacuum Generation 2 with the help of Audio Generator.

Thank you
Rafal

**Comment by dgiese** [comment]
You can look into the CN to EU conversion script. It contains the english voice files of Gen2.

**Comment by kowalczykrafal** [comment]
Thank you.
What is the difference between the EU and CN software?
Only sound? Are there other things?

**Comment by dgiese** [comment]
All the difference is in the conversion script ;)
