### ISSUE TITLE
php5 error on install

### ISSUE THREAD

**Issue by heartsaver1859** [dgiese/dustcloud#93]
There is an erorr with your install commands file. 
The error was  PHP Fatal error:  Uncaught Error: Class 'MySQLi' not found in /var/www/html/dustcloud/index.php:20\nStack trace:\n#0 {main}\n  thrown in /var/www/html/dustcloud/index.php on line 20

It could be fixed with adding php5-mysqlnd to apt-get install apache2 php5 php5-mysqlnd mysql-server python3 python3-pip git

**Comment by dgiese** [comment]
Moved to the wiki and added the package.
